<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Reservation;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRoomsDispo($start_date,$end_date)
    {
        $qb=$this->createQueryBuilder('p');
        $qb->select('p.id')
            ->innerJoin('p.reservations','a')
            ->where('a.startDate BETWEEN :d1 AND :d2' )
            ->orWhere('a.endDate BETWEEN :d1 AND :d2' )
            ->groupBy('p.id')
            ->setParameter('d1', $start_date)
            ->setParameter('d2', $end_date);


        return $qb->getQuery();
    }
}
